// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MicroServClient is the client API for MicroServ service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MicroServClient interface {
	Handle(ctx context.Context, in *ServRequest, opts ...grpc.CallOption) (*ServReply, error)
}

type microServClient struct {
	cc grpc.ClientConnInterface
}

func NewMicroServClient(cc grpc.ClientConnInterface) MicroServClient {
	return &microServClient{cc}
}

func (c *microServClient) Handle(ctx context.Context, in *ServRequest, opts ...grpc.CallOption) (*ServReply, error) {
	out := new(ServReply)
	err := c.cc.Invoke(ctx, "/protobuf.MicroServ/Handle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MicroServServer is the server API for MicroServ service.
// All implementations must embed UnimplementedMicroServServer
// for forward compatibility
type MicroServServer interface {
	Handle(context.Context, *ServRequest) (*ServReply, error)
	mustEmbedUnimplementedMicroServServer()
}

// UnimplementedMicroServServer must be embedded to have forward compatible implementations.
type UnimplementedMicroServServer struct {
}

func (UnimplementedMicroServServer) Handle(context.Context, *ServRequest) (*ServReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handle not implemented")
}
func (UnimplementedMicroServServer) mustEmbedUnimplementedMicroServServer() {}

// UnsafeMicroServServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MicroServServer will
// result in compilation errors.
type UnsafeMicroServServer interface {
	mustEmbedUnimplementedMicroServServer()
}

func RegisterMicroServServer(s grpc.ServiceRegistrar, srv MicroServServer) {
	s.RegisterService(&MicroServ_ServiceDesc, srv)
}

func _MicroServ_Handle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MicroServServer).Handle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.MicroServ/Handle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MicroServServer).Handle(ctx, req.(*ServRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MicroServ_ServiceDesc is the grpc.ServiceDesc for MicroServ service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MicroServ_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.MicroServ",
	HandlerType: (*MicroServServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handle",
			Handler:    _MicroServ_Handle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "micro-serv.proto",
}
